### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-js-collect-and-display-information-kPt9Fl#1]
@egillespie Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) (feel free to change it) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] Show a preview of the dating profile with rendered HTML (e.g. `<em>hella charming</em>` should appear as _hella charming_)
- [x] Also show the raw, generated HTML inside the `<pre><code></code></pre>` elements (e.g. `<em>hella charming</em>` should appear as `<em>hella charming</em>`)
- [x] Both the preview and raw HTML should update live as the user enters their information
- [x] All JavaScript is in a separate `.js` file
- [x] There are no linting errors in your JavaScript (this will also be expected for all future projects)

Javascript tested with npm's standard, not the atom linting.

**Comment by chrisvfritz** [comment]
Looking very nice! This is great-looking good. 🍭  I definitely don't mind if the linting is done from the command line or from Atom. The result is the same. 🙂 

### Issues in generated HTML

Just a couple small issues in the generated HTML. First, the indentation on this paragraph is a little off and the closing `</p>` tag actually has the `/` in the wrong place 🙈 : 

``` js
'<p>' +
  desc.value +
  '  <p/>' +
```

The correct indentation might look more like:

``` js
'<p>' + 
  desc.value + 
'</p>' +
```

I also notice there's not an opening `<p>` tag for the contact info.

**Comment by lordcrekit** [comment]
I totally butchered the template when converting it, and deleted one of the `</p>s.` I thought one of the `<p>`s was being used as a line break (that happens in javadocs a lot), and I'm OCD unclosed tags so I made it auto-close.

Anyway, fixed that.

**Comment by chrisvfritz** [comment]
Magnifique! 🎉 :shipit:
